package.json, src/App.tsx, yarn.lock
Built the project with yarn and scss file was successfully compiled to css.
=> Added bulma CSS framework and Sass workflow

package.json, src/App.tsx, src/components/Modal.tsx, src/index.tsx, src/views/ModalTest.tsx, yarn.lock
Create Modal component and ModalTest view
=> Build the Proof-of-Concept Modals

.github/workflows/main.yml, .stylelintrc.json, .vscode/settings.json, package.json, src/App.scss, src/components/modals/Modals.scss, yarn.lock
=> Chore: add SASS linter functionality

package.json, src/components/dashboard/dashboard-list/DashboardList.tsx, yarn.lock
The dashboard will now auto-populate the applicant list by making a GET request to the /applicant endpoint.
A GET request will be performed once after the DashboardList mounts, followed by another GET every 60 seconds.
=> Get applicants

src/components/login/LoginForm.tsx, src/components/login/SignUpForm.tsx, src/views/Login.scss, src/views/Login.tsx
Created mode state in Login View, which decides to render Sign Up or Login forms.
=> Implemented Sign Up view

package.json, src/components/home/HomeBanner.scss, src/components/home/HomeBanner.tsx, src/index.tsx, src/views/Home.scss, src/views/Home.tsx, yarn.lock
=> Implemented basic HomeBanner

src/components/sidebar/SideBar.tsx, src/components/sidebar/SideBarLink.tsx, src/components/sidebar/Sidebar.scss, src/views/Dashboard.scss, src/views/Dashboard.tsx
Updated to represent Figma wireframes with a few changes
=> Updated dashboard UI with some clean-up

src/components/dashboard/dashboard-list/DashboardList.tsx, src/views/Dashboard.tsx
- API call to the backend has been moved from the DashboardList component to the Dashboard view
- The Dashboard view now passes the list of applicants to the DashboardList component via props
=> Fetch applicants from dashboard view

src/components/applicant/ApplicantInfo.scss, src/components/applicant/ApplicantInfo.tsx, src/components/scoring/Scoring.scss, src/components/scoring/Scoring.tsx, src/components/scoring/ScoringForm.scss, src/components/scoring/ScoringForm.tsx, src/components/scoring/ScoringFormOption.tsx, src/views/Dashboard.tsx
-Add form to score applicants
-Temporary design until hi-fi designs are provided
-Add button to open scoring from applicant info
-Upgrade scoring page to hi-fi
=> Dashboard Scoring Component

src/components/scoring/ScoringForm.scss, src/components/scoring/ScoringForm.tsx, src/components/scoring/ScoringFormOption.tsx
Due to my last commit the scss created a conflict affecting login forms
The css was changing all elements with the class 'field', not only the ones from the scoring form, so I just changed the class name
=> Fix css conflict in form field

src/components/applicant/ApplicantInfo.scss, src/components/applicant/ApplicantInfo.tsx, src/components/scoring/Scoring.scss, src/components/scoring/Scoring.tsx, src/components/scoring/ScoringForm.scss, src/components/scoring/ScoringForm.tsx, src/components/scoring/ScoringFormOption.tsx, src/components/scoring/ScoringModal.scss, src/components/scoring/ScoringModal.tsx, src/components/scoring/ScoringNavbar.scss, src/components/scoring/ScoringNavbar.tsx, src/views/Dashboard.tsx, yarn.lock
Update Scoring page to reflect new design
Add modal to confirm submission
Create Current Score  functionality
=> Update UI/scoring page

src/components/auth/GoogleLoginButton.tsx, src/components/options/Options.scss, src/components/options/Options.tsx, src/components/options/SheetListCard.scss, src/views/Dashboard.tsx
=> Updated API calls to reflect database updates

package.json, src/components/applicant/ApplicantInfo.tsx, src/components/dashboard/dashboard-list/DashboardList.tsx, src/components/dashboard/dashboard-list/DashboardListCard.tsx, src/components/modals/ApplicantManagementModal.tsx, src/views/Dashboard.tsx
These are some initial changes about the mailing API call on the client-side. Currently, it failed to go through the backend due to some issues with the auth process.
Potential workarounds: SendGrid or Mailchimp
=> Mail sending PoC to backend API

src/components/dashboard/dashboard-list/DashboardList.tsx, src/components/dashboard/dashboard-list/DashboardListCard.scss, src/components/dashboard/dashboard-list/DashboardListCard.tsx
Pretty much working, Bulma likes to space out evenly on the view, but its not going to break anything so I won't bother to fix... yet:
If I pack in some applicants it looks better:
=> Changed Dashboard List to Two Columns

src/App.tsx, src/views/MobileUIWarning.scss, src/views/MobileUIWarning.tsx
We never really designed or implemented a mobile UI so I will disable access to the app on these viewports
=> App no longer tries to render mobile UI

src/components/dashboard/dashboard-list/DashboardList.tsx
I didn't apply this to the rest of the dashboard cards - but it's here now! :)
=> Fix 2 Column Change

src/components/sidebar/SideBar.tsx
Pretty common thing to see on lots of web applications
=> Clicking Logo in Sidebar Now Redirects to the Landing Page

src/App.tsx, src/components/archive/ArchiveHeader.scss, src/components/archive/ArchiveHeader.tsx, src/components/archive/ArchiveList.scss, src/components/archive/ArchiveList.tsx, src/components/dashboard/dashboard-list/DashboardList.tsx, src/components/dashboard/dashboard-list/DashboardListCard.tsx, src/views/Archive.tsx, src/views/Dashboard.tsx
=> Implemented archive view

src/App.tsx
=> Login route

src/App.tsx, src/components/auth/AuthUtil.tsx, src/components/sidebar/SideBar.tsx
=> Logout flow

src/App.tsx
I broke the build due to merge conflict fixing on the web GUI, now I unbroke it
=> Fixing broken build due to auto merge conflict resolve

src/components/dashboard/dashboard-list/DashboardListCard.tsx, src/components/scoring/InterviewForm.tsx, src/views/Archive.tsx, src/views/Dashboard.tsx
Also fixed a minor bug, so that the correct logo (based on their role) was displayed for each applicant.
Closes #155
=> Added Interview Score to Card

src/components/home/DescriptionSection.tsx, src/components/home/FeaturesSection.scss
Filbert requested a few more minor changes in the home page
=> Small fix on landing UI
